In [83]:
import numpy as np
import perfplot
from numba import njit
from sklearn.datasets import make_regression
import pandas as pd
from scipy.linalg.blas import dgemm
import scipy.linalg as sl
%load_ext snakeviz


The snakeviz extension is already loaded. To reload it, use:
  %reload_ext snakeviz


In [11]:
#2
#generating data for ols
#np.random.seed(25)
variables = 50
nobs = 20000


#def generate_data_ols(nobs, variables):
    
#    means = np.ones(variables)
#    cov = np.eye(variables) + np.ones((variables, variables)) * 0.2
#    x = np.random.multivariate_normal(mean=means, cov=cov, size=nobs)
#    e = np.random.randn(nobs)
#    true_beta = np.random.uniform(-0.99, 0.99, variables)
#    y = x @ true_beta + e

#    return x, y

def generate_data_ols(nobs, variables):
    x, y, coef = make_regression(n_samples=nobs, n_features=variables, n_informative=variables, 
                    effective_rank=None, noise=0.4, shuffle=True, coef=True, random_state=25)
    return x, y, coef

#next steps
#add more implementations using factorisation and spicy
#go on to timing and the other assignment and come back to put everything together
#after all is done fix the other problems



In [12]:
x, y, coef = generate_data_ols(nobs, variables)
x, y, coef

(array([[ 6.53717255e-01, -2.86299195e+00,  4.49643557e-01, ...,
         -8.03092092e-01,  1.81554710e+00,  9.34609956e-01],
        [ 3.96684874e-02, -1.30676025e+00, -2.08085875e+00, ...,
         -5.92928434e-01, -1.04328929e+00,  1.13565534e-01],
        [ 4.43738703e-01, -2.87689834e+00,  2.16870842e-03, ...,
          1.52404394e+00,  4.26721146e-01, -6.37186400e-01],
        ...,
        [ 8.77854741e-02,  7.21123808e-01, -1.84289771e-01, ...,
          1.01052466e+00, -6.55915068e-01,  3.46075638e-02],
        [ 9.76738329e-01,  1.91974900e-01, -7.52095211e-01, ...,
         -1.78340734e+00,  4.41242680e-02, -1.56801849e+00],
        [ 1.23997263e+00,  6.31279143e-01, -2.76662645e-01, ...,
          2.76027227e+00, -1.66727037e+00, -3.12841244e-01]]),
 array([ 4.68705055e+01, -3.06675087e+02, -4.61400131e-01, ...,
         3.90342302e+02,  6.28295735e+02, -5.80269603e+02]),
 array([12.89122851, 99.42609075, 39.69812146, 96.15839456, 13.16011288,
        21.70198703, 69.9007772

In [57]:


"""Define different implementations of OLS using numpy and numpy and spicy.

Each implementation returns the estimated parameter vector.

"""
#---------numpy implementations---------------
#mathematical implemantation numpy
@njit
def matrix_inversion_np(x, y):
    beta = np.linalg.inv(x.T.dot(x)).dot(x.T.dot(y))
    return beta

# least squares implementation numpy
@njit
def lstsq_np(x, y):
    beta = np.linalg.lstsq(x, y)[0]
    return beta

#pseudo inverse implementation numpy
@njit
def pseudo_inverse_np(x, y):
    beta = np.dot(np.linalg.pinv(x), y)
    return beta

# Solve a linear matrix equation, or system of linear scalar equations with numpy.
# this is only valid if x has full rank which is not always the case.
@njit
def solve_np(x,y):
    beta = np.linalg.solve(np.dot(x.T, x), np.dot(x.T, y))
    return beta

def lls_with_blas(x, y, residuals=False):
    """
    https://gist.github.com/aldro61/5889795
    """
    #a, b, coef = generate_data_ols(nobs, variables) - a, b are x, y
    i = dgemm(alpha=1.0, a=a.T, b=a.T, trans_b=True)
    beta = np.linalg.solve(i, dgemm(alpha=1.0, a=a.T, b=b)).flatten()
    return beta

#---------spicy implementations----------------
#matrix multiplication implementation spicy
#@njit
def matrix_inversion_spicy(x, y):
    beta = sl.inv(x.T.dot(x)).dot(x.T.dot(y))
    return beta

# least squares implementation spicy
@njit
def lstsq_spicy(x, y):
    beta = np.linalg.lstsq(x, y)[0]    
    return beta

#pseudo inverse implementation spicy
@njit
def pseudo_inverse_spicy(x, y):
    beta = np.dot(sl.pinv(x), y)
    return beta

# Solve a linear matrix equation, or system of linear scalar equations with spicy.
# this is only valid if x has full rank which is not always the case.
#@njit
def solve_spicy(x,y):
    beta = sl.solve(np.dot(x.T, x), np.dot(x.T, y))
    return beta



In [58]:
a, b, coef = generate_data_ols(nobs, variables)
a, b, coef

(array([[ 6.53717255e-01, -2.86299195e+00,  4.49643557e-01, ...,
         -8.03092092e-01,  1.81554710e+00,  9.34609956e-01],
        [ 3.96684874e-02, -1.30676025e+00, -2.08085875e+00, ...,
         -5.92928434e-01, -1.04328929e+00,  1.13565534e-01],
        [ 4.43738703e-01, -2.87689834e+00,  2.16870842e-03, ...,
          1.52404394e+00,  4.26721146e-01, -6.37186400e-01],
        ...,
        [ 8.77854741e-02,  7.21123808e-01, -1.84289771e-01, ...,
          1.01052466e+00, -6.55915068e-01,  3.46075638e-02],
        [ 9.76738329e-01,  1.91974900e-01, -7.52095211e-01, ...,
         -1.78340734e+00,  4.41242680e-02, -1.56801849e+00],
        [ 1.23997263e+00,  6.31279143e-01, -2.76662645e-01, ...,
          2.76027227e+00, -1.66727037e+00, -3.12841244e-01]]),
 array([ 4.68705055e+01, -3.06675087e+02, -4.61400131e-01, ...,
         3.90342302e+02,  6.28295735e+02, -5.80269603e+02]),
 array([12.89122851, 99.42609075, 39.69812146, 96.15839456, 13.16011288,
        21.70198703, 69.9007772

In [90]:
#timing the different implementations

time_result = %timeit -o matrix_inversion_np(x,y)
time_result = %timeit -o matrix_inversion_spicy(x,y)
time_result = %timeit -o lstsq_np(x,y)
time_result = %timeit -o lstsq_spicy(x,y)
time_result = %timeit -o pseudo_inverse_np(x,y)
##time_result = %timeit -o pseudo_inverse_spicy(x,y)
time_result = %timeit -o solve_np(x,y)
time_result = %timeit -o solve_spicy(x,y)
#time_result = %timeit -o lls_with_blas(x,y)

average_time = np.mean(time_result.timings)
average_time

7.74 ms ± 240 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)
7.65 ms ± 349 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)
35.7 ms ± 1.25 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)
36 ms ± 1.28 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)
87.5 ms ± 6.58 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)
7.84 ms ± 297 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)
7.6 ms ± 309 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


0.007604577714285239

In [93]:
a = np.arange(300,20000,600)
a

array([  300,   900,  1500,  2100,  2700,  3300,  3900,  4500,  5100,
        5700,  6300,  6900,  7500,  8100,  8700,  9300,  9900, 10500,
       11100, 11700, 12300, 12900, 13500, 14100, 14700, 15300, 15900,
       16500, 17100, 17700, 18300, 18900, 19500])